### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by nubs** [nubs/docker-php-minimal#1]

**Comment by francis826** [comment]
I'd love a basic README on this! I'm trying to build php 4.3.3 in a docker container but I'm not sure how exactly you're going about this.

**Comment by nubs** [comment]
I'll try to put something together tomorrow :)

**Comment by nubs** [comment]
@francis826, I added a README - please let me know if you need any assistance or if I can help in any way.

**Comment by francis826** [comment]
@nubs Thanks a bunch! :) 

(I'm hoping commenting doesn't re-open this "issue")

**Comment by nubs** [comment]
Glad I could help.
