### ISSUE TITLE
4.3.11 museum.php.net appears down

### ISSUE THREAD

**Issue by yieme** [nubs/docker-php-minimal#3]
I need 4.3.x for a legacy project and was excited to find your docker project. Unfortunately it appears museum.php.net isn't serving except to redirect to https:// and then 404's on the .gz file. Thoughts?

**Comment by nubs** [comment]
Hrm, strange.  It is not 404ing for me.  This link does not work for you?  http://museum.php.net/php4/php-4.3.11.tar.gz

I was just able to build a docker image for php 4.3.0 and 4.3.11, so it should be possible.

**Comment by nubs** [comment]
@yieme, were you able to get this working for you?

**Comment by nubs** [comment]
I'm going to close this.  Feel free to reopen it if you are still having problems.

**Comment by yieme** [comment]
@nubs, I just tried again and was able to get it to download. Thank you for looking into this :-)

**Comment by nubs** [comment]
no problem, glad you were able to get it working :)
